title: Jared Nicastro - AI & Product
description: Enthusiast in AI, building cool projects. 
theme: jekyll-theme-minimal

# Social Links (uncomment and add your usernames)
# github_username: yourusername
# twitter_username: yourusername
# linkedin_username: yourusername
# email: your.email@example.com
